In [1]:
import numpy as np

In [2]:
it=[2,6,7,11]

In [3]:
n=np.array(it)

In [4]:
type(n)

numpy.ndarray

In [17]:
twod=np.array([[1,2,5],[3,4,5]])
twod.shape

(2, 3)

In [13]:
y=np.array([2,5,6,"77"])

In [14]:
y

array(['2', '5', '6', '77'], dtype='<U11')

In [20]:
twod.shape

(2, 3)

In [19]:
twod.size

6

In [28]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
np.arange(7,12,2)

array([ 7,  9, 11])

In [29]:
np.array(range(7))

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
arr=np.arange(40)

In [40]:
brr=arr.reshape(8,5)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [41]:
arr[0]=1000

In [43]:
arr

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [44]:
brr

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [45]:
arr is brr

False